language: ruby
rvm:
- 2.2.0
addons:
  code_climate:
    repo_token: 6dc582455b3529d44dde0bf265ef5903a05cbbeb20341f4c6825bfaa7a111493
  postgresql: "9.3"
env:
  - DB=postgres
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres  
deploy:
  provider: heroku
  app: telao
  api_key:
    secure: XhFF5UEvdovHNK5wMyQaPuCCpoFsvdaDImlz50NvIqs7MT0izPkM99JaldafkvzzbAqs90X4cIcA+woivTByusgH0UOT9B91nxK8lYmVeuK4ThRb+xJ5Y0vXrqXE9qFGV/+5Lj8IunHhECHrw6PjP2TVDL2z5gl9erSUIh67xTE=
