language: ruby
rvm:
  - 2.2.0
addons:
  code_climate:
    repo_token: 6dc582455b3529d44dde0bf265ef5903a05cbbeb20341f4c6825bfaa7a111493
deploy:
  provider: heroku
  app: telao
  api_key:
    secure: Ywt596AjohWjOtt14gpnzG9kyLTp+fiOY6Z1i07PHhaiOyoIhv41u5r+yTDhJCjcDw8R+2yOzWBa8igoL+lgJDaw4nTUV+GnFVcW/noFB65LDyjIbvUXGvWdYIN1Y9SpVsm4D9l2WkSUJsyHvFVQOQ1kIJj4zEdxB6LVtnsJeic=
    secure: 
