language: ruby

rvm:
  - 2.2.1

addons:
  code_climate:
    repo_token: 6dc582455b3529d44dde0bf265ef5903a05cbbeb20341f4c6825bfaa7a111493
  postgresql: 9.3

env:
  - DB=postgres
  - "TEST_GROUP=1"
  - "TEST_GROUP=2"
  - "TEST_GROUP=3"
  - "TEST_GROUP=4"
  - "TEST_GROUP=5"
  - "TEST_GROUP=6"

script:
  - bundle exec parallel_test spec/ -n 6 --only-group $TEST_GROUP --group-by filesize --type rspec

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres

deploy:
  provider: heroku
  api_key:
    secure: Ia36DG3qwkP9m/T8poznvUL8s7iHu72NRm9LqWgY/Yl0vcEOCx2Lfh3jNYRL+6bbvNUHd6Eyg4tp/U1U11JK1LP31AcV013PazCtu3MCofYBB5sNZQSrdDm17a9xAeVbrGuywAQnzAF48n+0GPtJ8/ANU/JRfCsoGLrZg+8AlSQ=
  app: telao
  on:
    repo: brunoocasali/interactive-event
  run:
      - "rake db:create"
      - "rake db:migrate"
      - restart
