---
development:
  cloud_name: brunoocasali
  api_key: '721491713742652'
  api_secret: vS1P66uAcODP94u6q2kor_4fDc0
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: brunoocasali
  api_key: '721491713742652'
  api_secret: vS1P66uAcODP94u6q2kor_4fDc0
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: brunoocasali
  api_key: '721491713742652'
  api_secret: vS1P66uAcODP94u6q2kor_4fDc0
  enhance_image_tag: true
  static_image_support: false
