default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: bruno
  password: '[ 09 postgresbruno ]'

development:
  <<: *default
  database: repense_asi_development

test:
  <<: *default
  database: repense_asi_test<%= ENV['TEST_ENV_NUMBER'] %>

