default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: bruno
  password: '[ 09 postgresbruno ]'

development:
  <<: *default
  database: interactive_wedding_development

test:
  <<: *default
  database: interactive_wedding_test<%= ENV['TEST_ENV_NUMBER'] %>

