default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  port: 5432
  username: postgres
  password: '[ 09 archbruno ]'

development:
  <<: *default
  database: interactive_wedding_development

test:
  <<: *default
  database: interactive_wedding_test<%= ENV['TEST_ENV_NUMBER'] %>

