default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  port: 5432
  username: bruno
  password: '[ 09 osbruno ]'

development:
  <<: *default
  database: interactive_event_development

production:
  <<: *default
  database: interactive_event_production

test:
  <<: *default
  database: interactive_event_test<%= ENV['TEST_ENV_NUMBER'] %>

